services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: "andrew"
      MYSQL_PASSWORD: "andrew"
      MYSQL_DATABASE: "flask-crud"
      MYSQL_ROOT_PASSWORD: "andrew1230"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "/var/lib/mysql"